# -*- coding: utf-8 -*-
"""fl_client

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ykI0PvDwlZpezL-mLxqqVqFS0lVp4MI5
"""

# src/fl_client.py
import sys
sys.path.append('./drive/MyDrive/fed-hospital-project/src/') # Add the correct path to Python path
import base64 as _b64 
import flwr as fl, torch, numpy as np, hashlib, pickle
import baseline_client, update_utils
from baseline_client import TabularMLP, train_local_mlp

def state_to_list(state):
    return [state[k] for k in sorted(state.keys())]

class FLClient(fl.client.NumPyClient):
    def __init__(self, cid, X_tr, y_tr, X_val, y_val, privkey_path=None):
        self.cid=int(cid)
        self.X_tr=X_tr; self.y_tr=y_tr
        self.X_val=X_val; self.y_val=y_val
        self.model=TabularMLP(X_tr.shape[1])
        self.privkey=update_utils.load_private_key(privkey_path) if privkey_path else None

    def get_parameters(self,config=None):
        return [v.detach().cpu().numpy() for v in self.model.state_dict().values()]

    def fit(self, parameters, config):
        keys=list(self.model.state_dict().keys())
        state={k:parameters[i] for i,k in enumerate(keys)}
        self.model.load_state_dict({k:torch.tensor(v) for k,v in state.items()})
        new_state,n_samples,loss=train_local_mlp(self.X_tr,self.y_tr,epochs=3,global_state=state)
        numpy_state = update_utils.state_dict_to_numpy(new_state)
        blob = update_utils.serialize_numpy_state(numpy_state)
        sig = update_utils.sign_bytes(self.privkey, blob) if self.privkey else None
        sig_b64 = _b64.b64encode(sig).decode() if sig is not None else None
        sys.stderr.write(f"[DEBUG FL_CLIENT] Type of self.privkey: {type(self.privkey)}")
        sys.stderr.flush()
        sys.stderr.write(f"[DEBUG FL_CLIENT] Type of blob: {type(blob)}")
        sys.stderr.flush()
        sys.stderr.write(f"[DEBUG FL_CLIENT] Length of blob: {len(blob)}")
        sys.stderr.flush()
        blob_b64= _b64.b64encode(blob).decode()
        params_list=state_to_list(new_state)
        metrics={"loss":float(loss),"signature_b64":sig_b64,"serialized_blob_b64":blob_b64}
        return params_list,n_samples,metrics

    def evaluate(self, parameters, config):
        keys=list(self.model.state_dict().keys())
        state={k:parameters[i] for i,k in enumerate(keys)}
        acc=baseline_client.eval_local_mlp(state,self.X_val,self.y_val)
        return 0.0,len(self.X_val),{"accuracy":acc}
