# -*- coding: utf-8 -*-
"""fl_server

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v04HMCfifc1tpfIzZTj-BqlClloKcsSy
"""



import flwr as fl
print("✅ Flower version:", fl.__version__)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/fed-hospital-project/src

import warnings
warnings.filterwarnings("ignore", message="DEPRECATED FEATURE")

import os
import flwr as fl
from server_aggregator import AccountableFedAvg

PROJECT_ROOT = "/content/drive/MyDrive/fed-hospital-project"

if __name__ == "__main__":
    # Ensure directories exist
    os.makedirs(os.path.join(PROJECT_ROOT, "outputs", "global_weights"), exist_ok=True)
    os.makedirs(os.path.join(PROJECT_ROOT, "outputs", "evidence"), exist_ok=True)

    # Initialize the custom accountable FedAvg strategy
    strategy = AccountableFedAvg(
        gm_url="http://localhost:5001/open",
        save_root=PROJECT_ROOT
    )

    print("--> Starting Flower Server (AccountableFedAvg) on port 9091 ...")

    # Start the Flower federated learning server
    fl.server.start_server(
        server_address="0.0.0.0:9091",
        config=fl.server.ServerConfig(num_rounds=3),
        strategy=strategy
    )

